version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies"
      - npm ci

  build:
    commands:
      - echo "Building Vite React app"
      - npm run build

  post_build:
    commands:
      - echo "Deploy to S3"
      - aws s3 sync build s3://aivle-class1-group1-bucket --delete
      - echo "Invalidate CloudFront cache"
      - aws cloudfront create-invalidation --distribution-id E15NJWDFIPN8VW --paths "/*"

artifacts:
  files:
    - '**/*'
  base-directory: build
